version: '3.8'

services:
  financial-news-analysis:
    build: .
    container_name: financial-news-analysis
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
