name: Run Unit Tests

on:
  push:
    branches:
      - task-1
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=$GITHUB_WORKSPACE/ta-lib
          make
          make install
          export C_INCLUDE_PATH=$GITHUB_WORKSPACE/ta-lib/include
          export LIBRARY_PATH=$GITHUB_WORKSPACE/ta-lib/lib
          pip install -r requirements.txt


      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./tests/test-reports/
